language: node_js
node_js:
  - "node"
#sudo: true
dist: trusty

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - yarn lint
  - yarn build --base-href /debroodjes/
  - mv dist/debroodjes/index.html dist/debroodjes/404.html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist/debroodjes
  on:
    branch: master
