language: node_js
node_js:
  - "node"
#sudo: true
dist: trusty

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - npm install
  - ng build --prod --base-href=/debroodjes

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: dist/debroodjes
  on:
    branch: master
